[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true

[alias]
	s = status

	a = add
	aa = add --all
	unst = restore --staged

	cm = commit -m
	uncm = reset --soft HEAD^
	cma = commit --amend --no-edit

	ch = checkout
	new = checkout -b

	psc = !git push origin $(git rev-parse --abbrev-ref HEAD)
	plc = !git pull origin $(git rev-parse --abbrev-ref HEAD)

	fo = fetch origin

	d = diff
	l = log --oneline
	lg = log --graph --oneline --all
